Vagrant.configure("2") do |config|

    config.vm.define :sonex do |sonex_config|
        sonex_config.vm.box = "ubuntu/jammy64"
        sonex_config.vm.host_name = "sonex"
        sonex_config.vm.network "private_network", ip:"192.168.56.150"
  
      config.vm.provider "virtualbox" do |vb|
        vb.name = "sonex"
        vb.gui = false
        vb.cpus = "4"
        vb.memory = "6144"
      end
  
      config.vm.provision "shell" do |shell|
        shell.path = "sonex.sh"
      end
    end
  end