Vagrant.configure("2") do |config|

  config.vm.define :jenkins do |jenkins_config|
    jenkins_config.vm.box = "ubuntu/jammy64"
    jenkins_config.vm.host_name = "jenkins"
    jenkins_config.vm.network "private_network", ip:"192.168.56.100"

    config.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins"
      vb.gui = false
      vb.cpus = "4"
      vb.memory = "4096"
    end

    config.vm.provision "shell" do |shell|
      shell.path = "jenkins.sh"
    end
  end
end